### ISSUE TITLE
Remove imports.add(com.yelp.android.BuildConfig)

### ISSUE THREAD

**Issue by raducom** [Yelp/parcelgen#34]
Remove imports.add(com.yelp.android.BuildConfig) on line 234, this is a hardcoded import that will cause issues if the script is being used with another package. We need it just to log out some stuff if in debug mode, we can get rid of those lines for now.

**Comment by redwarp** [comment]
Hum, I have the same problem. Would be nice if this would go away.

**Comment by jbrick** [comment]
The solution to this is probably just to do the same thing in debug as in production. The error reporting won't be as nice but I don't think it's a big deal.

**Comment by jbrick** [comment]
Should be fixed now.
