### ISSUE TITLE
enum: Inconsistency when naming values.

### ISSUE THREAD

**Issue by redwarp** [Yelp/parcelgen#36]
When declaring an enum a .json file, after running parcel gen, the different values of the enum are created in PascalCase.

This is rather inconsistent with the generic consensus for this, which would be to use SCREAMING_SNAKE_CASE.

And actually, in our Yelp apps, we 99% of the time use the SCREAMING_SNAKE_CASE.
The official java tutorial (https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html) uses that as well.

**Comment by jbrick** [comment]
Should be fixed now.
